### ISSUE TITLE
『徵才』Junior Web Developer

### ISSUE THREAD

**Issue by sidraw27** [pi-tw/jobs#1]
# 團隊介紹

我們接受任何新技術，以便創造任何可能性

團隊中有經驗豐富的系統架構師、專業的資料科學家、社群活躍的高手等
在這裡你可以看到我們用Golang當作系統上效能瓶頸的solution、Laravel開發我們的網站、Python來處理資料分析的工作，只要是能夠解決問題的技術我們都不排斥

### Tech Stacks

- PHP、Python、Golang、Vue、React
- MongoDB、MySQL、Elasticsearch、Redis、Memcached
- Kafka、RabbitMQ
- Nginx、Varnish
- Linux、Docker
- Git、GitLab
- GCP

# 工作地點

高雄市三民區博愛一路391號6F

# 工作內容

* 開發並維護網站
* 撰寫爬蟲
* 系統維運
* 與PM溝通並實做功能

# 技能要求

* 不限學經歷但希望你是對資訊技術有熱情及好奇心
* 持續學習並精進自我
* 基本網路概念
* 能夠解決基礎問題的能力

# 薪資

TWD 32,000 ~ 38,000

# 應徵方式

請備履歷寄送至
sidraw@3.1416.tw
開頭請註明應徵職缺

**Comment by dsewnr** [comment]
履歷格式有沒有限制？

**Comment by sidraw27** [comment]
@dsewnr 
為了讓大家揮灑創意，基本上沒有限制，
但是你也知道的，從履歷可以看出應徵者的個性或是做事的方式，
可能多少會有影響哦

**Comment by D3annyC** [comment]
羨慕

**Comment by Hash543** [comment]
感覺是個很靈活的公司，發展不受限
對於新手應該可以學到很多東西

**Comment by sidraw27** [comment]
謝謝！ 也歡迎分享
