### ISSUE TITLE
『徵才』Junior Web Developer

### ISSUE THREAD

**Issue by dsewnr** [pi-tw/jobs#4]
### 歡迎應屆畢業新鮮人加入 ###
# 團隊介紹

我們接受任何新技術，以創造任何可能性
 
團隊中有經驗豐富的系統架構師、專業的資料科學家、社群活躍的高手…等
在這裡你可以看到我們用 Laravel / Django 開發我們的網站，Scrapy 來爬資料，gensim、jieba …等工具來處理、分析資料，只要是能夠解決問題的技術我們都不排斥

### Tech Stacks

- PHP、Python、Golang
- Laravel、Django、Scrapy
- Vue、React、jQuery
- MongoDB、MySQL、PostgreSQL、Elasticsearch、Redis、Memcached
- Kafka、RabbitMQ
- Nginx、Varnish
- Linux、Docker、Drone
- Git、GitLab、Gogs
- GCP

# 工作地點

高雄市三民區博愛一路 391 號 6F

# 工作內容

* 開發並維護網站
* 撰寫爬蟲
* 系統維運
* 與 PM 溝通並實做功能

# 技能要求

* 基礎的英文閱讀能力
* 基本網路概念
* 不排斥並願意使用 Linux or macOS 的開發環境
* 不限學經歷但希望你是對資訊技術有熱情及好奇心
* 能夠發現並解決問題的能力
* 持續學習並精進自我

# 薪資

TWD 32,000 ~ 38,000

# 應徵方式

請備履歷寄送至
dsewnr@3.1416.tw
開頭請註明應徵職缺

**Comment by pkmogy** [comment]
現在還可以投履歷嗎?

**Comment by dsewnr** [comment]
> 現在還可以投履歷嗎?

職缺已關閉喔，如果有要徵才 PTT 還會再 PO 新文，謝謝。
